name: AWS deploy

on:
  push:
    branches: [ main ]

jobs:
  check:  
    name: checkfor status 200
    runs-on: ubuntu-latest
    needs: aws
    steps:
      - uses: actions/checkout@v2
      - id: text
        uses: johnlokerse/website-healthcheck@v2
        with:
          web-url: "http://${{ secrets.AWS_HOSTNAME }}"
          scan-for-text: "Hello from Flask App"
